/**
 * Tic Tac Toe
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Possible values for a board square. `.` means empty square.
 */
export const Mark = {
    Period: '.',
    X: 'X',
    O: 'O',
} as const;
export type Mark = typeof Mark[keyof typeof Mark];

