/**
 * Tic Tac Toe
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Mark } from './mark';
import { Winner } from './winner';


export interface Status { 
    winner?: Winner;
    board?: Array<Array<Mark>>;
}
export namespace Status {
}


