/**
 * Tic Tac Toe
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Winner of the game. `.` means nobody has won yet.
 */
export const Winner = {
    Period: '.',
    X: 'X',
    O: 'O',
} as const;
export type Winner = typeof Winner[keyof typeof Winner];

